'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class DisplayValueLookups
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FexmanNet.DisplayValueLookups", GetType(DisplayValueLookups).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Off
        '''Stack
        '''Combo
        '''Tube.
        '''</summary>
        Friend Shared ReadOnly Property AmpType() As String
            Get
                Return ResourceManager.GetString("AmpType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1
        '''2
        '''3
        '''4
        '''5
        '''6
        '''7
        '''8
        '''9
        '''10
        '''12
        '''14
        '''16
        '''18
        '''20
        '''23
        '''26
        '''30
        '''35
        '''40.
        '''</summary>
        Friend Shared ReadOnly Property AttackTime() As String
            Get
                Return ResourceManager.GetString("AttackTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1.0
        '''1.5
        '''2.0
        '''3.0
        '''5.0
        '''7.0
        '''10.0
        '''20.0.
        '''</summary>
        Friend Shared ReadOnly Property CompressionRatio() As String
            Get
                Return ResourceManager.GetString("CompressionRatio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0.1ms
        '''1.7ms
        '''3.2ms
        '''4.8ms
        '''6.4ms
        '''8.0ms
        '''9.5ms
        '''11.1ms
        '''12.7ms
        '''14.3ms
        '''15.8ms
        '''17.4ms
        '''19.0ms
        '''20.6ms
        '''22.1ms
        '''23.7ms
        '''25.3ms
        '''26.9ms
        '''28.4ms
        '''30.0ms
        '''31.6ms
        '''33.2ms
        '''34.7ms
        '''36.3ms
        '''37.9ms
        '''39.5ms
        '''41.0ms
        '''42.6ms
        '''44.2ms
        '''45.7ms
        '''47.3ms
        '''48.9ms
        '''50.5ms
        '''52.0ms
        '''53.6ms
        '''55.2ms
        '''56.8ms
        '''58.3ms
        '''59.9ms
        '''61.5ms
        '''63.1ms
        '''64.6ms
        '''66.2ms
        '''67.8ms
        '''69.4ms
        '''70.9ms
        '''72.5ms
        '''74.1ms
        '''75.7ms
        '''77.2ms
        '''78.8ms
        '''80.4ms
        '''81.9ms
        '''83.5ms
        '''85.1ms
        '''86.7ms
        '''88.2ms
        '''89.8ms
        '''91.4ms
        '''93.0ms
        '''94.5ms
        '''96.1ms
        '''97.7ms
        '''99.3ms.
        '''</summary>
        Friend Shared ReadOnly Property DelayTime200() As String
            Get
                Return ResourceManager.GetString("DelayTime200", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0.1ms
        '''0.3ms
        '''0.4ms
        '''0.6ms
        '''0.7ms
        '''0.9ms
        '''1.0ms
        '''1.2ms
        '''1.4ms
        '''1.5ms
        '''1.7ms
        '''1.8ms
        '''2.0ms
        '''2.1ms
        '''2.3ms
        '''2.5ms
        '''2.6ms
        '''2.8ms
        '''2.9ms
        '''3.1ms
        '''3.2ms
        '''3.4ms
        '''3.5ms
        '''3.7ms
        '''3.9ms
        '''4.0ms
        '''4.2ms
        '''4.3ms
        '''4.5ms
        '''4.6ms
        '''4.8ms
        '''5.0ms
        '''5.1ms
        '''5.3ms
        '''5.4ms
        '''5.6ms
        '''5.7ms
        '''5.9ms
        '''6.1ms
        '''6.2ms
        '''6.4ms
        '''6.5ms
        '''6.7ms
        '''6.8ms
        '''7.0ms
        '''100.9ms
        '''104.0ms
        '''107.2ms
        '''110.3ms
        '''113.5ms
        '''116.6ms
        '''119.8ms
        '''122.9ms
        '''126.1ms
        '''129.2ms
        '''132.4ms
        '''135.5ms
        '''138.6ms
        '''141.8ms
        '''144.9ms
        '''148.1ms
        '''151.2ms
        '''154.4ms
        '''157.5ms
        '''160.7ms
        '''163.8ms
        '''167.0ms        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property DelayTime400() As String
            Get
                Return ResourceManager.GetString("DelayTime400", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to S-H
        '''L-H
        '''Rdm
        '''Rvs
        '''Plt
        '''Spr.
        '''</summary>
        Friend Shared ReadOnly Property EarlyReflectionType() As String
            Get
                Return ResourceManager.GetString("EarlyReflectionType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to THRU
        '''22hz
        '''25hz
        '''28hz
        '''32hz
        '''36hz
        '''40hz
        '''45hz
        '''50hz
        '''56hz
        '''63hz
        '''70hz
        '''80hz
        '''90hz
        '''100hz
        '''110hz
        '''125hz
        '''140hz
        '''160hz
        '''180hz
        '''200hz
        '''225hz
        '''250hz
        '''280hz
        '''315hz
        '''355hz
        '''400hz
        '''450hz
        '''500hz
        '''560hz
        '''630hz
        '''700hz
        '''800hz
        '''900hz
        '''1.0khz
        '''1.1khz
        '''1.2khz
        '''1.4khz
        '''1.6khz
        '''1.8khz
        '''2.0khz
        '''2.2khz
        '''2.5khz
        '''2.8khz
        '''3.2khz
        '''3.6khz
        '''4.0khz
        '''4.5khz
        '''5.0kz
        '''5.6k
        '''6.3k
        '''7.0k
        '''8.0k
        '''9.0k
        '''10.0k
        '''11.0k
        '''12.0k
        '''14.0k
        '''16.0k
        '''18.0k
        '''THRU.
        '''</summary>
        Friend Shared ReadOnly Property EQFrequency() As String
            Get
                Return ResourceManager.GetString("EQFrequency", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thru
        '''PwrBs
        '''Radio
        '''TelePh
        '''Clean
        '''Low.
        '''</summary>
        Friend Shared ReadOnly Property FilterType() As String
            Get
                Return ResourceManager.GetString("FilterType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TypeA
        '''TypeB.
        '''</summary>
        Friend Shared ReadOnly Property GateType() As String
            Get
                Return ResourceManager.GetString("GateType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mono
        '''Stereo.
        '''</summary>
        Friend Shared ReadOnly Property InputMode() As String
            Get
                Return ResourceManager.GetString("InputMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Left
        '''Right
        '''L+R.
        '''</summary>
        Friend Shared ReadOnly Property InputSelect() As String
            Get
                Return ResourceManager.GetString("InputSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0.00
        '''0.04
        '''0.08
        '''0.13
        '''0.17
        '''0.21
        '''0.25
        '''0.29
        '''0.34
        '''0.38
        '''0.42
        '''0.46
        '''0.51
        '''0.55
        '''0.59
        '''0.63
        '''0.67
        '''0.72
        '''0.76
        '''0.80
        '''0.84
        '''0.88
        '''0.93
        '''0.97
        '''1.01
        '''1.05
        '''1.09
        '''1.14
        '''1.18
        '''1.22
        '''1.26
        '''1.30
        '''1.35
        '''1.39
        '''1.43
        '''1.47
        '''1.51
        '''1.56
        '''1.60
        '''1.64
        '''1.68
        '''1.72
        '''1.77
        '''1.81
        '''1.85
        '''1.89
        '''1.94
        '''1.98
        '''2.02
        '''2.06
        '''2.10
        '''2.15
        '''2.19
        '''2.23
        '''2.27
        '''2.31
        '''2.36
        '''2.40
        '''2.44
        '''2.48
        '''2.52
        '''2.57
        '''2.61
        '''2.65
        '''2.69
        '''2.78
        '''2.86
        '''2.94
        '''3.03
        '''3.11
        '''3.20
        '''3.28
        '''3.37
        '''3.45
        '''3.53
        '''3.62
        '''3.70
        '''3.87
        '''4.04
        '''4.21
        '''4.37
        '''4.54
        '''4.71
        '''4.88
        '''5.05
        '''5. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property LFOFrequency() As String
            Get
                Return ResourceManager.GetString("LFOFrequency", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0.0
        '''0.1
        '''0.2
        '''0.3
        '''0.4
        '''0.5
        '''0.6
        '''0.7
        '''0.8
        '''0.9
        '''1.0
        '''1.1
        '''1.2
        '''1.3
        '''1.4
        '''1.5
        '''1.6
        '''1.7
        '''1.8
        '''1.9
        '''2.0
        '''2.1
        '''2.2
        '''2.3
        '''2.4
        '''2.5
        '''2.6
        '''2.7
        '''2.8
        '''2.9
        '''3.0
        '''3.1
        '''3.2
        '''3.3
        '''3.4
        '''3.5
        '''3.6
        '''3.7
        '''3.8
        '''3.9
        '''4.0
        '''4.1
        '''4.2
        '''4.3
        '''4.4
        '''4.5
        '''4.6
        '''4.7
        '''4.8
        '''4.9
        '''5.0
        '''5.1
        '''5.2
        '''5.3
        '''5.4
        '''5.5
        '''5.6
        '''5.7
        '''5.8
        '''5.9
        '''6.0
        '''6.1
        '''6.2
        '''6.3
        '''6.4
        '''6.5
        '''6.6
        '''6.7
        '''6.8
        '''6.9
        '''7.0
        '''7.1
        '''7.2
        '''7.3
        '''7.4
        '''7.5
        '''7.6
        '''7.7
        '''7.8
        '''7.9
        '''8.0
        '''8.1
        '''8.2
        '''8.3
        '''8.4
        '''8.5
        '''8.6
        '''8.7
        '''8.8
        '''8.9
        '''9.0
        '''9.1
        '''9.2
        '''9.3
        '''9.4
        '''9.5
        '''9.6
        '''9.7
        '''9.8
        '''9.9
        '''10.0
        '''11.1
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property ModulationDelayOffset() As String
            Get
                Return ResourceManager.GetString("ModulationDelayOffset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Off
        '''On.
        '''</summary>
        Friend Shared ReadOnly Property OffOn() As String
            Get
                Return ResourceManager.GetString("OffOn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Normal
        '''Inverse.
        '''</summary>
        Friend Shared ReadOnly Property OutputPhase() As String
            Get
                Return ResourceManager.GetString("OutputPhase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to L&lt;&gt;R
        '''L&gt;R
        '''L&lt;R
        '''Lturn
        '''Rturn
        '''L/R.
        '''</summary>
        Friend Shared ReadOnly Property PanDirection() As String
            Get
                Return ResourceManager.GetString("PanDirection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 10
        '''15
        '''25
        '''35
        '''45
        '''55
        '''65
        '''75
        '''85
        '''100
        '''115
        '''140
        '''170
        '''230
        '''340
        '''680.
        '''</summary>
        Friend Shared ReadOnly Property ReleaseTime() As String
            Get
                Return ResourceManager.GetString("ReleaseTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0.3s
        '''0.4s
        '''0.5s
        '''0.6s
        '''0.7s
        '''0.8s
        '''0.9s
        '''1.0s
        '''1.1s
        '''1.2s
        '''1.3s
        '''1.4s
        '''1.5s
        '''1.6s
        '''1.7s
        '''1.8s
        '''1.9s
        '''2.0s
        '''2.1s
        '''2.2s
        '''2.3s
        '''2.4s
        '''2.5s
        '''2.6s
        '''2.7s
        '''2.8s
        '''2.9s
        '''3.0s
        '''3.1s
        '''3.2s
        '''3.3s
        '''3.4s
        '''3.5s
        '''3.6s
        '''3.7s
        '''3.8s
        '''3.9s
        '''4.0s
        '''4.1s
        '''4.2s
        '''4.3s
        '''4.4s
        '''4.5s
        '''4.6s
        '''4.7s
        '''4.8s
        '''4.9s
        '''5.0s
        '''5.5s
        '''6.0s
        '''6.5s
        '''7.0s
        '''7.5s
        '''8.0s
        '''8.5s
        '''9.0s
        '''9.5s
        '''10.0s
        '''11.0s
        '''12.0s
        '''13.0s
        '''14.0s
        '''15.0s
        '''16.0s
        '''17.0s
        '''18.0s
        '''19.0s
        '''20.0s
        '''25.0s
        '''30.0s.
        '''</summary>
        Friend Shared ReadOnly Property ReverbTime() As String
            Get
                Return ResourceManager.GetString("ReverbTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0.5m
        '''0.8m
        '''1.0m
        '''1.3m
        '''1.5m
        '''1.8m
        '''2.0m
        '''2.3m
        '''2.6m
        '''2.8m
        '''3.1m
        '''3.3m
        '''3.6m
        '''3.9m
        '''4.1m
        '''4.4m
        '''4.6m
        '''4.9m
        '''5.2m
        '''5.4m
        '''5.7m
        '''5.9m
        '''6.2m
        '''6.5m
        '''6.7m
        '''7.0m
        '''7.2m
        '''7.5m
        '''7.8m
        '''8.0m
        '''8.3m
        '''8.6m
        '''8.8m
        '''9.1m
        '''9.4m
        '''9.6m
        '''9.9m
        '''10.2m
        '''10.4m
        '''10.7m
        '''11.0m
        '''11.2m
        '''11.5m
        '''11.8m
        '''12.1m
        '''12.3m
        '''12.6m
        '''12.9m
        '''13.1m
        '''13.4m
        '''13.7m
        '''14.0m
        '''14.2m
        '''14.5m
        '''14.8m
        '''15.1m
        '''15.4m
        '''15.6m
        '''15.9m
        '''16.2m
        '''16.5m
        '''16.8m
        '''17.1m
        '''17.3m
        '''17.6m
        '''17.9m
        '''18.2m
        '''18.5m
        '''18.8m
        '''19.1m
        '''19.4m
        '''19.7m
        '''20.0m
        '''20.2m
        '''20.5m
        '''20.8m
        '''21.1m
        '''21.4m
        '''21. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property ReverbWDH() As String
            Get
                Return ResourceManager.GetString("ReverbWDH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0.1
        '''0.3
        '''0.4
        '''0.6
        '''0.7
        '''0.9
        '''1.0
        '''1.2
        '''1.4
        '''1.5
        '''1.7
        '''1.8
        '''2.0
        '''2.1
        '''2.3
        '''2.5
        '''2.6
        '''2.8
        '''2.9
        '''3.1
        '''3.2
        '''3.4
        '''3.5
        '''3.7
        '''3.9
        '''4.0
        '''4.2
        '''4.3
        '''4.5
        '''4.6
        '''4.8
        '''5.0
        '''5.1
        '''5.3
        '''5.4
        '''5.6
        '''5.7
        '''5.9
        '''6.1
        '''6.2
        '''6.4
        '''6.5
        '''6.7
        '''6.8
        '''7.0.
        '''</summary>
        Friend Shared ReadOnly Property RoomSize() As String
            Get
                Return ResourceManager.GetString("RoomSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A
        '''I
        '''U
        '''E
        '''O.
        '''</summary>
        Friend Shared ReadOnly Property VowelSound() As String
            Get
                Return ResourceManager.GetString("VowelSound", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
