'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class SW60
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FexmanNet.SW60", GetType(SW60).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0,0,0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0,No Effect
        '''65,0,38|39|10|41|0|21|22|23|24|6|0|0|0|0|40|0,Chorus1
        '''65,1,38|39|10|41|0|21|22|23|24|6|0|0|0|0|40|0,Chorus2
        '''65,2,38|39|10|41|0|21|22|23|24|6|0|0|0|0|40|0,Chorus3
        '''65,8,38|39|10|41|0|21|22|23|24|6|0|0|0|0|40|0,Chorus4
        '''66,0,38|39|10|41|0|21|22|23|24|6|0|0|0|0|40|0,Celeste1
        '''66,1,38|39|10|41|0|21|22|23|24|6|0|0|0|0|40|0,Celeste2
        '''66,2,38|39|10|41|0|21|22|23|24|6|0|0|0|0|40|0,Celeste3
        '''66,8,38|39|10|41|0|21|22|23|24|6|0|0|0|0|40|0,Celeste4
        '''67,0,38|39|10|41|0|21 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property ChorusEffects() As String
            Get
                Return ResourceManager.GetString("ChorusEffects", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0,1,No Parameter,,
        '''0,69,Reverb Time,RvbTim,ReverbTime
        '''0,10,Diffusion,Diffus,
        '''0,63,Initial Delay,IniDly,DelayTime200
        '''0,52,HPF Cutoff,HPFCut,EQFrequency
        '''34,60,LPF Cutoff,LPFCut,EQFrequency
        '''1,127,Dry/Wet,DryWet,
        '''0,63,Rev Delay,RevDly,DelayTime200
        '''0,4,Density,Densty,
        '''1,127,Er/Rev Balance,E/RBal,
        '''1,127,Feedback Level,Feedbk,
        '''0,37,Width,Width,ReverbWDH
        '''0,73,Height,Height,ReverbWDH
        '''0,104,Depth,Depth,ReverbWDH
        '''0,30,Wall Vary,WalVar,
        '''1,14860,Left Delay,LftDly,DotOne
        '''1,14860,Right Delay,RgtDly,DotOne        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property EffectParameters() As String
            Get
                Return ResourceManager.GetString("EffectParameters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0,0,0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0,No Effect
        '''1,0,1|2|3|4|5|0|0|0|0|6|7|8|9|20|10|0,Hall1
        '''1,1,1|2|3|4|5|0|0|0|0|6|7|8|9|20|10|0,Hall2
        '''2,0,1|2|3|4|5|0|0|0|0|6|7|8|9|20|10|0,Room1
        '''2,1,1|2|3|4|5|0|0|0|0|6|7|8|9|20|10|0,Room2
        '''2,2,1|2|3|4|5|0|0|0|0|6|7|8|9|20|10|0,Room3
        '''3,0,1|2|3|4|5|0|0|0|0|6|7|8|9|20|10|0,Stage1
        '''3,1,1|2|3|4|5|0|0|0|0|6|7|8|9|20|10|0,Stage2
        '''4,0,1|2|3|4|5|0|0|0|0|6|7|8|9|20|10|0,Plate
        '''16,0,1|2|3|4|5|11|12|13|14|6|7|8|9|20|10|0,White Room
        '''17,0,1|2|3|4|5|11|12|13|14|6|7|8|9|20|10|0,Tunne [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property ReverbEffects() As String
            Get
                Return ResourceManager.GetString("ReverbEffects", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 64,0,0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0,Thru
        '''0,0,0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0,No Effect
        '''1,0,1|2|3|4|5|0|0|0|0|6|7|8|9|68|10|0,Hall1
        '''1,1,1|2|3|4|5|0|0|0|0|6|7|8|9|68|10|0,Hall2
        '''2,0,1|2|3|4|5|0|0|0|0|6|7|8|9|68|10|0,Room1
        '''2,1,1|2|3|4|5|0|0|0|0|6|7|8|9|68|10|0,Room2
        '''2,2,1|2|3|4|5|0|0|0|0|6|7|8|9|68|10|0,Room3
        '''3,0,1|2|3|4|5|0|0|0|0|6|7|8|9|68|10|0,Stage1
        '''3,1,1|2|3|4|5|0|0|0|0|6|7|8|9|68|10|0,Stage2
        '''4,0,1|2|3|4|5|0|0|0|0|6|7|8|9|68|10|0,Plate
        '''5,0,15|16|17|18|10|19|20|0|0|6|0|0|21|22|23|24,Delay L/C/R
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property VariationEffects() As String
            Get
                Return ResourceManager.GetString("VariationEffects", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
